export const typesObjOne = {
    id: 'Coffee',
    lightBg: false,
    lightText: false,
    lightTextDesc: true,
    TopLine: 'Coffee',
    Headline: 'light,Medium and Dark', 
    description: 'Light roast coffee is a light brown color and has no oil on the surface of the beans. These coffees typically have a crisp acidity, a mellow body, and bright flavors.',
    description2: 'Medium roast coffee is a brown color and rarely has an oily surface. These coffees have a medium acidity and body, as well as a rounded flavor profile.',
    description3:'Dark roast coffee is a dark brown color and often has an oily surface. These coffees have a low acidity, heavy body, and tend to reveal deeper, darker flavors.',
    buttonLabel: 'Get started',
    imgStart: false,
    img: require('../../images/coffeebeans.jpg').default,
    alt:'bag of coffee beans',
    dark: true,
    primary: true,
    darkText: false
};
export const typesObjTwo = {
    id: 'Methods',
    lightBg: false,
    lightText: false,
    lightTextDesc: true,
    TopLine: 'Methods',
    Headline: 'Methods', 
    description: 'French Press: Espro P3 | $ 35 - 45',
    description2: 'Pour Over: CHEMEX | $47.00',
    description3:'Machine Drip: Braun BrewSense | $90 - 100',
    buttonLabel: 'Get started',
    imgStart: false,
    img: require('../../images/coffeeMethods.jpg').default,
    alt:'bag of coffee beans',
    dark: true,
    primary: true,
    darkText: false
};
export const typesObjThree = {
    id: 'Brews',
    lightBg: false,
    lightText: false,
    lightTextDesc: true,
    TopLine: 'Brews',
    Headline: 'Methods, Grinds, water and Time', 
    description: ' French Press, Grind: Coarse, a 1:12 coffee-to-water ratio. If you are using 350 grams of water, you will want 30 grams of coffee and a target brew time between 6 and 8 minutes.',
    description2: 'Pour over, Grind: Medium-Coarse, a water to coffee ratio of 16:1 or 15:1 if you prefer a more potent cup. This means 16 grams of water for every gram of coffee.  and Keep the liquid level in the dripper between ½ and ¾ full. Avoid pouring along the edges of the coffee bed. Control brewing time and liquid level by slowing or speeding up the pour as needed; total brew time should be 3–4 minutes.',
    description3:'Machine Drip, Grind: Medium(sea salt), start with a 1:16 ratio. This means for every 16 ounces of water; 1 ounce of coffee is needed.A target brew time is approximately 5 minutes.',
    buttonLabel: 'Get started',
    imgStart: false,
    img: require('../../images/coffeebrew.jpg').default,
    alt:'bag of coffee beans',
    dark: true,
    primary: true,
    darkText: false
};